services:
    postgres-db:
        image: postgres:15
        container_name: postgres_db_travelroute
        ports: 
            - '5432:5432'
        networks:
             - my_network
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres123
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5  

networks:
    my_network:
        driver: bridge